#!/usr/bin/env python3
"""Generate INDEX.md — the human-readable atlas of named UI surfaces — from
atlas-codes.json. PORTED from the Unity rig's gen-index.py (registry-driven, so
it ports unchanged); only the doc link points at the web-stack coverage matrix.

Also generates DIGEST.md (a one-line-per-code digest of the captured set, if a
shots dir is given) so the captured atlas has both an INDEX (the registry) and a
DIGEST (what was actually captured).

Usage: gen-index.py                 # writes INDEX.md next to this script
       gen-index.py --check         # exit 1 if INDEX.md is stale (CI/pre-commit)
       gen-index.py --digest DIR    # also write DIGEST.md from captured PNGs in DIR
"""
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
REG = json.load(open(os.path.join(ROOT, "atlas-codes.json")))
AREAS = REG["areas"]
CODES = REG["codes"]


def render_index():
    # route->code -> group by area letter, ordered by the numeric code.
    by_area = {a: [] for a in AREAS}
    for route, code in CODES.items():
        by_area.setdefault(code[0], []).append((code, route))
    for rows in by_area.values():
        rows.sort(key=lambda r: r[0])

    out = [
        "# Atlas — named UI surfaces (web-stack bevy-overlay routes)",
        "",
        "<!-- GENERATED by gen-index.py from atlas-codes.json — do not edit by hand. -->",
        "",
        "Every distinct bevy-overlay UI surface the URL-walk reaches, by code. Each",
        "`<CODE>` names one screen; capture writes `<CODE>-<route>.png`. Routes are",
        "URL-addressable (`?panel=...`) — see [`routes.json`](routes.json). How the",
        "atlas is driven + the coverage rationale:",
        "[`../docs/00-coverage-matrix.md`](../docs/00-coverage-matrix.md).",
        "",
    ]
    for letter, name in AREAS.items():
        rows = by_area.get(letter, [])
        out.append(f"## {letter} — {name}")
        out.append("")
        out.append("| Code | Route |")
        out.append("|---|---|")
        for code, route in rows:
            out.append(f"| `{code}` | {route} |")
        out.append("")
    return "\n".join(out)


def render_digest(shots_dir):
    have = {}
    for f in sorted(glob.glob(os.path.join(shots_dir, "*.png"))):
        base = os.path.basename(f)[:-4]
        code = base.split("-", 1)[0]
        have[code] = base
    out = ["# Atlas DIGEST — captured set", "",
           f"<!-- GENERATED by gen-index.py --digest from {shots_dir} -->", ""]
    inv = {c: r for r, c in CODES.items()}
    for code in sorted(set(CODES.values())):
        route = inv.get(code, "?")
        mark = "captured" if code in have else "MISSING"
        out.append(f"- `{code}` {route} — {mark}")
    return "\n".join(out) + "\n"


def main():
    args = sys.argv[1:]
    path = os.path.join(ROOT, "INDEX.md")
    new = render_index()

    if "--digest" in args:
        i = args.index("--digest")
        shots = args[i + 1] if i + 1 < len(args) else os.environ.get(
            "DCL_ATLAS_OUT", os.path.join(ROOT, "shots", "atlas"))
        open(os.path.join(ROOT, "DIGEST.md"), "w").write(render_digest(shots))
        print(f"wrote {os.path.join(ROOT, 'DIGEST.md')} from {shots}")

    if "--check" in args:
        cur = open(path).read() if os.path.exists(path) else ""
        if cur != new:
            print("INDEX.md is stale — run atlas/gen-index.py", file=sys.stderr)
            sys.exit(1)
        print("INDEX.md up to date")
        return

    open(path, "w").write(new)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
